### ISSUE TITLE
AES and DES encryption with .Net 5 on Windows 10 throwing exception "Operation is not supported on this platform."

### ISSUE THREAD

**Issue by glenserraview** [lextudio/sharpsnmplib#146]
We have been using your library with .Net Framework, and are porting the app to .Net core.

Our first issue encountered was that AES was not supported on .Net core 3.x [as you reported](https://github.com/dotnet/runtime/issues/15771)

So we upgraded to .Net 5, but we're now receiving an "Operation is not supported on this platform" exception, with the call stack as shown below. This occurs for both AES and DES, as they both use the Helper.cs method to determine if it's supported.

Looking at the code, it appears that the SecuritySupported method of Helper needs to be updated to include .Net 5. Is that correct? Do you have any plans to support .Net 5?

```
public static bool SecuritySupported
        {
            get
            {
                if (securitySupported != null)
                {
                    return securitySupported.Value;
                }

                return (securitySupported = RuntimeInformation.FrameworkDescription.StartsWith(".NET Framework")).Value;
            }
        }
```

Call stack:
```
   at Lextm.SharpSnmpLib.Security.AESPrivacyProviderBase.Encrypt(Byte[] unencryptedData, Byte[] key, Int32 engineBoots, Int32 engineTime, Byte[] privacyParameters)
   at Lextm.SharpSnmpLib.Security.AESPrivacyProviderBase.Encrypt(ISnmpData data, SecurityParameters parameters)
   at Lextm.SharpSnmpLib.Security.PrivacyProviderExtension.GetScopeData(IPrivacyProvider privacy, Header header, SecurityParameters parameters, ISnmpData rawScopeData)
   at Lextm.SharpSnmpLib.Security.PrivacyProviderExtension.ComputeHash(IPrivacyProvider privacy, VersionCode version, Header header, SecurityParameters parameters, ISegment scope)
   at Lextm.SharpSnmpLib.Messaging.GetBulkRequestMessage..ctor(VersionCode version, Int32 messageId, Int32 requestId, OctetString userName, OctetString contextName, Int32 nonRepeaters, Int32 maxRepetitions, IList`1 variables, IPrivacyProvider privacy, Int32 maxMessageSize, ISnmpMessage report)
   at Lextm.SharpSnmpLib.Messaging.Messenger.BulkHasNext(VersionCode version, IPEndPoint receiver, OctetString community, OctetString contextName, Variable seed, Int32 timeout, Int32 maxRepetitions, IList`1& next, IPrivacyProvider privacy, ISnmpMessage& report)
   at Lextm.SharpSnmpLib.Messaging.Messenger.BulkWalk(VersionCode version, IPEndPoint endpoint, OctetString community, OctetString contextName, ObjectIdentifier table, IList`1 list, Int32 timeout, Int32 maxRepetitions, WalkMode mode, IPrivacyProvider privacy, ISnmpMessage report)
   at Serraview.Snmp.SharpSnmp.SharpSnmpExecutor.BulkWalk(IPEndPoint targetEndpoint, SnmpVersion version, String community, String oid, IList`1 vlist, Int32 timeOut, Int32 maxRepetitions, SnmpWalkMode walkMode, IPrivacyProvider priv, String contextName) in D:\dev\serraview.snmp\src\Serraview.Snmp\SharpSNMP\SharpSNMPExecutor.cs:line 161
```

**Comment by lextm** [comment]
Even .NET 5 does not fully implement AES (I just tested that). You still have to use BouncyCastle based providers, https://docs.sharpsnmp.com/tutorials/aes.html#providers-on-bouncy-castle

**Comment by glenserraview** [comment]
Thanks for your response. What a shame AES wasn't implemented fully! 

I'll look at using BouncyCastle. Thanks again.

**Comment by nothrow** [comment]
May I ask you on what exactly is missing in the AES implementation? 

I did implement the AES-CFB for net50, and successfully tested my snmpv3 implementation over it.

**Comment by nothrow** [comment]
`RijndaelManaged` is not supported, however, if you use `AesCryptoServiceProvider`, you're good to go for all OSes net50 supports.

**Comment by lextm** [comment]
@nothrow Thanks. I will provide a reproducible test case once I have time.
