### ISSUE TITLE
Using snmp v3 and privacy protocol aes on .net core throws  PlatformNotSupportedException

### ISSUE THREAD

**Issue by juottha** [lextudio/sharpsnmplib#152]
When running on linux with Microsoft.NETCore.App 3.1.12 installed I get an exception, if AES privacy protocol is used. I''m using the latest version(12.3.0) of sharpsnmplib. 

Details:
System.PlatformNotSupportedException: Operation is not supported on this platform.
Stacktrace: Lextm.SharpSnmpLib.Security.AESPrivacyProviderBase.Encrypt(Byte[] unencryptedData, Byte[] key, Int32 engineBoots, Int32 engineTime, Byte[] privacyParameters)
   at Lextm.SharpSnmpLib.Security.AESPrivacyProviderBase.Encrypt(ISnmpData data, SecurityParameters parameters)
   at Lextm.SharpSnmpLib.Security.PrivacyProviderExtension.ComputeHash(IPrivacyProvider privacy, VersionCode version, Header header, SecurityParameters parameters, ISegment scope)
   at Lextm.SharpSnmpLib.Messaging.GetNextRequestMessage..ctor(VersionCode version, Int32 messageId, Int32 requestId, OctetString userName, OctetString contextName, IList`1 variables, IPrivacyProvider privacy, Int32 maxMessageSize, ISnmpMessage report)

It seems the code actively does it :
Encrypt does : 

            if (!IsSupported)
            {
                throw new PlatformNotSupportedException();
            }

And IsSupported eventually does this:

         return (securitySupported = RuntimeInformation.FrameworkDescription.StartsWith(".NET Framework")).Value

Doesn't .net core support AES or why IsSupported done like this ? It'd be great to have AES working on .net core as well.

**Comment by lextm** [comment]
"Doesn't .net core support AES"? No, it doesn't.

https://docs.sharpsnmp.com/tutorials/aes.html#providers-on-bouncy-castle
