### ISSUE TITLE
TargetInvocationException

### ISSUE THREAD

**Issue by sjbeskur** [lextudio/sharpsnmplib#158]
At unpredictable intervals the library throws this error when issuing a Walk command to a specific device.   I'm running on Linux (Ubuntu) with dotnet --version 5.0.103.   Any guidance would be greatly appreciated. 

Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Lextm.SharpSnmpLib.SnmpException: data construction exception
 ---> System.ArgumentException: Truncation error for 32-bit integer coding. (Parameter 'length')
   at Lextm.SharpSnmpLib.Integer32..ctor(Tuple`2 length, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   --- End of inner exception stack trace ---
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Stream stream)
   at Lextm.SharpSnmpLib.ResponsePdu..ctor(Tuple`2 length, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Stream stream)
   at Lextm.SharpSnmpLib.Sequence..ctor(Tuple`2 length, Stream stream)
   at Lextm.SharpSnmpLib.DataFactory.CreateSnmpData(Int32 type, Stream stream)
   at Lextm.SharpSnmpLib.Messaging.MessageFactory.ParseMessage(Int32 first, Stream stream, UserRegistry registry)
   at Lextm.SharpSnmpLib.Messaging.MessageFactory.ParseMessages(Byte[] buffer, Int32 index, Int32 length, UserRegistry registry)
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, UserRegistry registry, Socket udpSocket)
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, Socket udpSocket)
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver)
   at Lextm.SharpSnmpLib.Messaging.Messenger.HasNext(VersionCode version, IPEndPoint endpoint, OctetString community, Variable seed, Int32 timeout, Variable& next)
   at Lextm.SharpSnmpLib.Messaging.Messenger.Walk(VersionCode version, IPEndPoint endpoint, OctetString community, ObjectIdentifier table, IList`1 list, Int32 timeout, WalkMode mode)
   at LanTopology.Topology.Snmp.Walk(IPAddress target, String OID) in /home/sjbeskur/repos/sandbox/LanTopology/Topology/Snmp.cs:line 51
   at LanTopology.Topology.NetworkMapper.Run(String target, String community) in /home/sjbeskur/repos/sandbox/LanTopology/Topology/NetworkMapper.cs:line 20
   at LanTopology.Program.HandleScan(String target, String community, IConsole console, CancellationToken cancellationToken) in /home/sjbeskur/repos/sandbox/LanTopology/Program.cs:line 114
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by sjbeskur** [comment]
Well I have tracked this down to a single line in the Integer32 class that check for a byte array length 

line 99
`
if (length.Item1 > 4)
{
    throw new ArgumentException("Truncation error for 32-bit integer coding.", name(length));
}
`
If I change the if condition to check for` if (length.Item1 > 5)` then everything works as expected.   That said am not certain I that I've not introduced more issues.   This is particularly difficult to debug as it only seems to happen with MicroTik devices and the error does not occur everytime but does happen frequently. (I've tested with three of the most recent MicroTik firmware versions) 

Would love to hear any feedback anyone might offer.

**Comment by lextm** [comment]
Related to #30

**Comment by sjbeskur** [comment]
Messanger.UseFullRange = false;   

fixed the issue.   

`           var result = new List<Variable>();
            Messenger.UseFullRange = false;
            Messenger.Walk(Version,
                new IPEndPoint(target, Port),
                new OctetString(Community),
                new ObjectIdentifier(OID),
                result,
                TimeoutSecs * 1000,
                WalkMode.WithinSubtree
            );
            return result;
`

Thank you for your response.
