### ISSUE TITLE
Wrong Response Sequence

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#264]
I am getting an error when running Get requests on a device and need to know what the error indicates. If I do a Walk using a MIB browser after I get this issue I can get all the data. It is only #SNMP that has an issue.

Details:

I am calling Messenger.Get using SNMP V1 and I am querying 24 SNMP objects.

Exception:
{"wrong response sequence: expected -1986527, received 14790689"}

StackTrace:
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, UserRegistry registry, Socket udpSocket) in c:\sharpsnmplib\SharpSnmpLib\Messaging\SnmpMessageExtension.cs:line 440
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, Socket udpSocket) in c:\sharpsnmplib\SharpSnmpLib\Messaging\SnmpMessageExtension.cs:line 355
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver) in c:\sharpsnmplib\SharpSnmpLib\Messaging\SnmpMessageExtension.cs:line 320
   at Lextm.SharpSnmpLib.Messaging.Messenger.Get(VersionCode version, IPEndPoint endpoint, OctetString community, IList`1 variables, Int32 timeout) in c:\sharpsnmplib\SharpSnmpLib\Messaging\Messenger.cs:line 96
   at Comms.Snmp.SharpSNMPDevice.ProcessSnmpGets() in z:\Projects\SES Astra\2400 Program\Software\Source\SESAstraServer\SESAstraServer\Comms\Snmp\SharpSNMPDevice.cs:line 892

Please advise.

**Original Reported Date**: 2014-12-12T03:30:14.887-08:00
**Planned For Release**: TritonMate Refresh (8.5)
**Original CodePlex ID**: 7268

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Can you show what is the code in `ProcessSnmpGets`? If not, I can only close this issue as duplicate.

**Original Posted Date**: 2015-05-22T23:36:39.837-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Can you check `TestResponsesFromSingleSourceWithMultipleThreads` in this file,

https://github.com/lextm/sharpsnmplib/blob/master/Tests/Messaging/Tests/GetRequestMessageTestFixture.cs

The correct way to send multiple requests to a single agent is what this test case shows, by using a dedicate `Socket` object per threads. In that way each threads has its own buffer to receive the reply.

I left some comments there to show how to produce a "wrong sequence number" exception. That exception is expected, when using a single `Socket` to send out multiple requests. A buffer shared by all threads will allow one thread's reply being processed by another thread.

**Original Posted Date**: 2015-05-23T03:14:56.627-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Meanwhile, if you do use `Manager.Get` as the exception call stack shows, you might switch to the latest release (where each call to `Get` will create a new `Socket` object). Some very old releases do not do that.

Make sure `timeout` value is large enough, or there might be `TimeoutException` raised when you send a lot of requests to a single agent and it could not respond all of them quickly enough.

**Original Posted Date**: 2015-05-23T03:39:00.547-07:00

**Comment by lextudio-support** [comment]
**Original Closed Date**: 2015-09-24T05:00:14.937-07:00
