### ISSUE TITLE
SnmpTrapd.exe - Exception - Wrong user class constructor syntax

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#289]
I downloaded the latest source sharpsnmplib_213dd1a20aad and compiled. After some hack in the sln file I was able to compile the project and samples. When I ran the SnmpTrapd.exe it failed with the following exception.

#################
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.Practices.Unity.Configuration.dll

Additional information: Configuration is incorrect, the type Lextm.SharpSnmpLib.Security.User does not have a constructor that takes parameters named name, authentication, authenticationPhrase, privacy, privacyPhrase.
#################

It looks like the constructor for class User is User(OctetString name, IPrivacyProvider privacy), however we are trying to call it as User(OctetString name, string authentication, OctetString authenticationPhrase, string privacy, OctetString privacyPhrase).

The second syntax was found in older releases (like sharpsnmplib_a0b8834ec8d5), but no more available in new releases. I am not familiar with Unity framework or editing the app.config file , so was not able to fix it. 

Please fix it or give me a lead to fix it .

**Original Reported Date**: 2011-01-07T05:18:19.37-08:00
**Planned For Release**: 
**Original CodePlex ID**: 7214

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Just fixed in the latest build. Forgot to fix snmptrapd.exe.config along with others. Thanks for the report.

**Original Posted Date**: 2011-01-08T17:26:16.953-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Thanks. a lot  It runs fine now. 

But I had to add following two lines to the program.cs to make it compile.
using Lextm.SharpSnmpLib;
using Lextm.SharpSnmpLib.Security;

**Original Posted Date**: 2011-01-10T04:04:35.99-08:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi I am having the same issue with vb.net sample while compiling. I only know vb.net but dont know how to handle this issue. Your valuable input and help required. 

Thanks in advance.


-----Error Details--------------------------------------------------------------------
System.InvalidOperationException was unhandled
  Message=Configuration is incorrect, the type Lextm.SharpSnmpLib.Security.User does not have a constructor that takes parameters named name, authentication, authenticationPhrase, privacy, privacyPhrase.
  Source=Microsoft.Practices.Unity.Configuration
  StackTrace:
       at Microsoft.Practices.Unity.Configuration.ConstructorElement.GuardIsMatchingConstructor(Type typeToConstruct, ConstructorInfo ctor)
       at Microsoft.Practices.Unity.Configuration.ConstructorElement.GetInjectionMembers(IUnityContainer container, Type fromType, Type toType, String name)
       at Microsoft.Practices.Unity.Configuration.RegisterElement.<>c__DisplayClass1.<ConfigureContainer>b__0(InjectionMemberElement m)
       at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Microsoft.Practices.Unity.Configuration.RegisterElement.ConfigureContainer(IUnityContainer container)
       at Microsoft.Practices.Unity.Configuration.ContainerConfiguringElement.ConfigureContainerInternal(IUnityContainer container)
       at Microsoft.Practices.Unity.Configuration.ContainerElement.<>c__DisplayClass1.<ConfigureContainer>b__0(ContainerConfiguringElement element)
       at Microsoft.Practices.ObjectBuilder2.EnumerableExtensions.ForEach[TItem](IEnumerable`1 sequence, Action`1 action)
       at Microsoft.Practices.Unity.Configuration.ContainerElement.ConfigureContainer(IUnityContainer container)
       at Microsoft.Practices.Unity.Configuration.UnityConfigurationSection.Configure(IUnityContainer container, String configuredContainerName)
       at Microsoft.Practices.Unity.Configuration.UnityContainerExtensions.LoadConfiguration(IUnityContainer container, UnityConfigurationSection section, String containerName)
       at Microsoft.Practices.Unity.Configuration.UnityContainerExtensions.LoadConfiguration(IUnityContainer container, String containerName)
       at snmptrapd.Program.Main(String[] args) in C:\sharpsnmplib\Samples\VB.NET\snmptrapd\Program.vb:line 39
       at System.AppDomain._nExecuteAssembly(Assembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

-------End Error Details --------------------





-----Start of the code used-------------------------------------------

Imports System.Net
Imports Lextm.SharpSnmpLib
Imports Lextm.SharpSnmpLib.Pipeline
Imports Lextm.SharpSnmpLib.Security
Imports Lextm.SharpSnmpLib.Messaging
Imports Microsoft.Practices.Unity
Imports Microsoft.Practices.Unity.Configuration


Module Program
    Private m_Container As IUnityContainer

    Friend Property Container() As IUnityContainer
        Get
            Return m_Container

        End Get
        Private Set(ByVal value As IUnityContainer)
            m_Container = value
        End Set
    End Property

    Public Sub Main(ByVal args As String())


        If args.Length <> 0 Then
            Return
        End If


        Container = New UnityContainer().LoadConfiguration("snmptrapd")

        Dim users = Program.Container.Resolve(Of UserRegistry)()
        users.Add(New OctetString("neither"), DefaultPrivacyProvider.DefaultPair)
        users.Add(New OctetString("authen"), New DefaultPrivacyProvider(New MD5AuthenticationProvider(New OctetString("authentication"))))
        users.Add(New OctetString("privacy"), New DESPrivacyProvider(New OctetString("privacyphrase"), New MD5AuthenticationProvider(New OctetString("authentication"))))

        Dim trapv1 = Container.Resolve(Of TrapV1MessageHandler)("TrapV1Handler")
        AddHandler trapv1.MessageReceived, AddressOf WatcherTrapV1Received
        Dim trapv2 = Container.Resolve(Of TrapV2MessageHandler)("TrapV2Handler")
        AddHandler trapv2.MessageReceived, AddressOf WatcherTrapV2Received
        Dim inform = Container.Resolve(Of InformRequestMessageHandler)("InformHandler")
        AddHandler inform.MessageReceived, AddressOf WatcherInformRequestReceived
        Using engine = Container.Resolve(Of SnmpEngine)()
            engine.Listener.AddBinding(New IPEndPoint(IPAddress.Any, 162))
            engine.Start()
            Console.WriteLine("#SNMP is available at http://sharpsnmplib.codeplex.com")
            Console.WriteLine("Press any key to stop . . . ")
            Console.Read()
            engine.[Stop]()
        End Using
    End Sub

    Private Sub WatcherInformRequestReceived(ByVal sender As Object, ByVal e As InformRequestMessageReceivedEventArgs)
        Console.WriteLine(e.InformRequestMessage)
    End Sub

    Private Sub WatcherTrapV2Received(ByVal sender As Object, ByVal e As TrapV2MessageReceivedEventArgs)
        Console.WriteLine(e.TrapV2Message)
    End Sub

    Private Sub WatcherTrapV1Received(ByVal sender As Object, ByVal e As TrapV1MessageReceivedEventArgs)
        Console.WriteLine(e.TrapV1Message)
    End Sub

End Module


-----End of the Code Used--------------------------------------------------------------------------

**Original Posted Date**: 2011-05-21T16:27:48.437-07:00

**Comment by lextudio-support** [comment]
**Original Closed Date**: 2011-01-07T18:22:19.243-08:00
