### ISSUE TITLE
Further investigate the SocketAsyncEventArgs related exception

### ISSUE THREAD

**Issue by lextm** [lextudio/sharpsnmplib#44]
Continue the investigation in #43.

**Comment by lextm** [comment]
The initial exception was
```
Error Message:
 System.InvalidOperationException : An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.
Stack Trace:
   at System.Net.Sockets.SocketAsyncEventArgs.StartConfiguring()
   at System.Net.Sockets.SocketAsyncEventArgs.SetBufferInternal(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Sockets.SocketAsyncEventArgs.SetBuffer(Byte[] buffer, Int32 offset, Int32 count)
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.<SendAsync>d__13.MoveNext() in C:\projects\sharpsnmplib\SharpSnmpLib\Messaging\SnmpMessageExtension.cs:line 550
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.<SendAsync>d__12.MoveNext() in C:\projects\sharpsnmplib\SharpSnmpLib\Messaging\SnmpMessageExtension.cs:line 511
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Lextm.SharpSnmpLib.Integration.TrapDaemonTestFixture.<TestTrapV2HandlerWithV3Message>d__2.MoveNext() in C:\projects\sharpsnmplib\Tests\Integration\TrapDaemonTestFixture.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
as https://ci.appveyor.com/project/lextm/sharpsnmplib/build/1.0.171 shows.

However, deep down inside, the exception was a `NullReferenceException` when `Socket` is closed/disposed.
```
{System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Sockets.SocketAsyncEventArgs.InnerStartOperationReceiveMessageFrom()
   at System.Net.Sockets.Socket.ReceiveMessageFromAsync(SocketAsyncEventArgs e)
   at Lextm.SharpSnmpLib.Messaging.SocketExtension.ReceiveMessageFromAsync(Socket socket, SocketAwaitable awaitable) in C:\Users\lextm\Downloads\sharpsnmplib\SharpSnmpLib\Messaging\SocketExtension.cs:line 11
   at Lextm.SharpSnmpLib.Messaging.Discoverer.<ReceiveAsync>d__18.MoveNext() in C:\Users\lextm\Downloads\sharpsnmplib\SharpSnmpLib\Messaging\Discoverer.cs:line 389}
```

**Comment by lextm** [comment]
Fired a bug report to Microsoft and wait for their resolution,

https://github.com/dotnet/corefx/issues/21995

**Comment by lextm** [comment]
#136 introduced an important change, so please test out 12.0 release and provide feedback there.
