### ISSUE TITLE
"Wrong response sequence" OperationException

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#550]
Hi,  
  
Got an issue with the use of SharpSnmpLib: I often (~50% of times) got an
exception when doing a simple SNMP GET:  
  
Message:  

    
    
    wrong response sequence: expected -1649357291, received -1632514283

StackTrace:  

    
    
    at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, UserRegistry registry, Socket udpSocket)
    at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver, Socket udpSocket)
    at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse(ISnmpMessage request, Int32 timeout, IPEndPoint receiver)
    at Lextm.SharpSnmpLib.Messaging.Messenger.Get(VersionCode version, IPEndPoint endpoint, OctetString community, IList`1 variables, Int32 timeout)
    at ConsoleApplication1.Program.Main(String[] args) in C:\ConsoleApplication1\Program.cs:line 20

This is my code:  

    
    
    static void Main(string[] args) {
        var endPoint = new IPEndPoint(IPAddress.Parse("192.168.109.10"), 161);
        var variablesGet = new List<Variable> {
            new Variable(new ObjectIdentifier(".1.3.6.1.4.1.27359.12.10.6.1.3.18"))
        };
        while (true) {
            try {
                var result = Messenger.Get(
                        VersionCode.V1,
                        endPoint,
                        new OctetString("public"),
                        variablesGet, 
                        0);
                Console.WriteLine(result[0].Data);
            } catch (Exception ex) {
                Console.WriteLine(ex.Message.ToString());
            }
            Console.ReadLine();
        }
    }

This snippet is a simple Console application. What is weird is that when it
works for the first time, it will work every time for the same console
session. And when an exception is raised for the first time, it won't work for
the entire console session.  
  
Here the SNMP GET succeeds, and each one succeeds after I hit Enter:  
![Image](http://i.imgur.com/HawXphL.png)  
Here the SNMP GET fails, and each one fails after I hit Enter:  
![Image](http://i.imgur.com/z4oKnhO.png)  
  
Any idea why the GET fails?  
  
PS: I use TritonMate (8.0) version. The same behavior happens with the SET
command.  

**Original Reported Date**: 2013-12-16T02:51:49.05-08:00
**Original CodePlex Discussion Thread ID**: 474253

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

It has been reported a while ago but I could not reproduce it locally.  
  
Can you try to capture some network packets?
[https://sharpsnmplib.codeplex.com/wikipage?title=600008&referringTitle;=KB](https://sharpsnmplib.codeplex.com/wikipage?title=600008&referringTitle=KB)
In order to correlate the captured network packets and the errors you get, you
might also add time stamps to your console output. Then combining the two we
might find out what happens under the hood.  



**Original Posted Date**: 2013-12-28T05:18:56.44-08:00
