### ISSUE TITLE
Cannot use the NUnit unit tests of the Project

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#593]
I compiled the SharpSnmpLib project with VS2008 successfully. I was trying to
open the NUnit project in order to run the unit tests of the project but I
cannot open it. It shows me an exception message:

    
    
    System.IO.FileNotFoundException: Could not load file or assembly 'SharpSnmp:ib.Tests' or one of its dependencies. The system cannot find the file specified. 
    
    For further information, use the Exception Details menu item.

The exception details are:

System.IO.FileNotFoundException...

Server stack trace:

   at System.Reflection.Assembly._nLoad(AssemblyName fileName, String
codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawlMark&
stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)

   at System.Reflection.Assembly.InternalLoad(AssemblyName assemblyRef,
Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean
forIntrospection)

   at System.Reflection.Assembly.InternalLoad(String assemblyString, Evidence
assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)

   at System.Reflection.Assembly.Load(String assemblyString)

   at NUnit.Core.Builders.TestAssemblyBuilder.Load(String path)

   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName,
Boolean autoSuites)

   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName,
String testName, Boolean autoSuites)

   at NUnit.Core.TestSuiteBuilder.BuildSingleAssembly(TestPackage package)

   at NUnit.Core.TestSuiteBuilder.Build(TestPackage package)

   at NUnit.Core.SimpleTestRunner.Load(TestPackage package)

   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)

   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)

   at NUnit.Core.RemoteTestRunner.Load(TestPackage package)

   at
System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr
md, Object[] args, Object server, Int32 methodPtr, Boolean fExecuteInContext,
Object[]& outArgs)

   at
System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage
msg, Int32 methodPtr, Boolean fExecuteInContext)

Exception rethrown at [0]:

   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage
reqMsg, IMessage retMsg)

   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData&
msgData, Int32 type)

   at NUnit.Core.TestRunner.Load(TestPackage package)

   at NUnit.Util.TestDomain.Load(TestPackage package)

   at NUnit.Util.TestLoader.LoadTest(String testName)

    
    
    System.IO.FileNotFoundException...
    
    Server stack trace: 
       at System.Reflection.Assembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)
       at System.Reflection.Assembly.InternalLoad(AssemblyName assemblyRef, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
       at System.Reflection.Assembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
       at System.Reflection.Assembly.Load(String assemblyString)
       at NUnit.Core.Builders.TestAssemblyBuilder.Load(String path)
       at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, Boolean autoSuites)
       at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, String testName, Boolean autoSuites)
       at NUnit.Core.TestSuiteBuilder.BuildSingleAssembly(TestPackage package)
       at NUnit.Core.TestSuiteBuilder.Build(TestPackage package)
       at NUnit.Core.SimpleTestRunner.Load(TestPackage package)
       at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
       at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
       at NUnit.Core.RemoteTestRunner.Load(TestPackage package)
       at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Int32 methodPtr, Boolean fExecuteInContext, Object[]& outArgs)
       at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg, Int32 methodPtr, Boolean fExecuteInContext)
    
    Exception rethrown at [0]: 
       at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
       at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
       at NUnit.Core.TestRunner.Load(TestPackage package)
       at NUnit.Util.TestDomain.Load(TestPackage package)
       at NUnit.Util.TestLoader.LoadTest(String testName)
    

Has any body seen this before? Please help me on this. Thank you!

**Original Reported Date**: 2009-10-15T16:51:23.96-07:00
**Original CodePlex Discussion Thread ID**: 72164

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi,

no problems here with unit testing with nUnit.

Have you installed latest version of nUnit?

Does your source code compiles correctly?

Exception seems related to nUnit not able to load compiled assembly containing
unit tests.



Hope this helps,

Andrea



**Original Posted Date**: 2009-10-16T02:44:20.54-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi,

Also note that some test cases require an SNMP agent to be available locally.
It is bad dependency, but I could not find a way to replace them. :)

Good luck.

Lex



**Original Posted Date**: 2009-10-16T03:02:22.137-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi all,

Thank you guys for your help. I have solved my issue installing TestDriven.Net
in order to run NUnit in the VS IDE.

Now I can run the unit tests.

Thank you again!

Mauricio



**Original Posted Date**: 2009-10-16T07:17:16.01-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T20:59:17.16-07:00
