### ISSUE TITLE
Crash of Mib Browser, trying to load a specific MIB

### ISSUE THREAD

**Issue by lextudio-support** [lextudio/sharpsnmplib#685]
Hello!

I'm trying to do a C# software which read some data over a SNMP server (among
other things). So I tried to read the data from this server with #SNMP Mib
Browser, as I will use the same API.

When I try to load the MIB file I need to use with this server with MIB
Browser 6.1.1, I got this:

    
    
    System.IndexOutOfRangeException: Index was outside the bounds of the array.
       at Lextm.SharpSnmpLib.Mib.ModuleLoader.ParseLine(String line, String module) in g:\sharpsnmplib\SharpSnmpLib\Mib\ModuleLoader.cs:line 61
       at Lextm.SharpSnmpLib.Mib.ModuleLoader..ctor(TextReader reader, String moduleName) in g:\sharpsnmplib\SharpSnmpLib\Mib\ModuleLoader.cs:line 38
       at Lextm.SharpSnmpLib.Mib.ObjectTree.PrepareFiles(IEnumerable`1 files) in g:\sharpsnmplib\SharpSnmpLib\Mib\ObjectTree.cs:line 81
       at Lextm.SharpSnmpLib.Mib.ReloadableObjectRegistry.LoadModuleFolder(String path) in g:\sharpsnmplib\SharpSnmpLib\Mib\ReloadableObjectRegistry.cs:line 79
       at Lextm.SharpSnmpLib.Mib.ReloadableObjectRegistry.Reload() in g:\sharpsnmplib\SharpSnmpLib\Mib\ReloadableObjectRegistry.cs:line 55
       at Lextm.SharpSnmpLib.Browser.ModuleListPanel.ActAddExecute(Object sender, EventArgs e) in g:\sharpsnmplib\Browser\ModuleListPanel.cs:line 133
       at Crad.Windows.Forms.Actions.Action.OnExecute(EventArgs e)
       at Crad.Windows.Forms.Actions.Action.DoExecute()
       at Crad.Windows.Forms.Actions.Action.handleClick(Object sender, EventArgs e)
       at Crad.Windows.Forms.Actions.Action.target_Click(Object sender, EventArgs e)
       at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
       at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
       at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
       at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
       at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
       at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
       at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
       at System.Windows.Forms.ToolStrip.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
    

Since it may be the MIB file which are bogus, I tried with iReasonning MIB
Browser. The MIB file works and I can see the SNMP server (which loaded the
MIB file too, so I think the file is good), read the values and all.

As #SNMP MIB Browser is open source, I got the source file and tried to
compile it and see by myself where it bugs when loading the MIB file.

I used this
http://sharpsnmplib.codeplex.com/wikipage?title=600005&referringTitle=KB to
try to compile myself but I got several errors. One of them refer to the need
of Gendarme (Mono), so I installed it but I still get errors:

 The "Gendarme" task failed unexpectedly.\r

At this point, I'm stuck...

OS: Windows 2008 R2

Visual studio 2010 Professionnal

Mono 2.6.7 (just in case)

Gendarme 2.11

If you have any clue about one of this problems (or both ;)), let me know.

Thanks in advance

G.E.

**Original Reported Date**: 2011-06-24T07:45:13.27-07:00
**Original CodePlex Discussion Thread ID**: 262668

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

Hi,

You may open a bug report at
http://sharpsnmplib.codeplex.com/workitem/list/basic and paste the MIB
document as an attachment.

Besides, the Gendarme failure is not a major thing. As I cannot reproduce it,
I can only assume it is a bug of Gendarme task,

<http://unintelligible.org/blog/2010/10/02/gendarme-msbuild-task/>

If it keeps failing, you make use debug.bat to build the source code, or
simply remove the Gendarme task from SharpSnmpLib.csproj.

Regards,

Lex



**Original Posted Date**: 2011-06-25T22:13:30.297-07:00

**Comment by lextudio-support** [comment]
**Copied from CodePlex without authors**:

I'm just so lame not getting the mib file need to be compiled before used into
mib browser

I got it when browsing and trying to debug myself the source (debug.bat indeed
solve most of the compilation problems, although there is some warning)

Thanks for the help and apologies for my lameness.

G.E.



**Original Posted Date**: 2011-06-27T08:33:14.123-07:00

**Comment by lextudio-support** [comment]
**Marked as Answer Date**: 2013-10-06T20:41:28.477-07:00
